Implement Error pages
chaintope/tapyrus-explorer pull request #143
Opened 2023-07-25 03:29 UTC by Yamaguchi

Show error page when 
- Path not found (404 page)
- Access to backend service fails

2023-07-31 08:26 UTC, rantan requested changes

2023-07-31 08:26 UTC, rantan commented on backend/actions/block_detail.js
> +    res.status(503).send('Service Temporary Ununavailable');
```suggestion
    res.status(503).send('Service Temporary Unavailable');
```

2023-07-31 08:26 UTC, rantan commented on backend/actions/block_detail.js
> +    res.status(503).send('Service Temporary Ununavailable');
```suggestion
    res.status(503).send('Service Temporary Unavailable');
```

2023-07-31 08:26 UTC, rantan commented on backend/actions/block_detail.js
> +    res.status(503).send('Service Temporary Ununavailable');
```suggestion
    res.status(503).send('Service Temporary Unavailable');
```

2023-07-31 08:26 UTC, rantan commented on backend/actions/transaction_detail.js
> +    res.status(503).send('Service Temporary Ununavailable');
```suggestion
    res.status(503).send('Service Temporary Unavailable');
```

2023-07-31 08:26 UTC, rantan commented on backend/actions/transaction_detail.js
> +    res.status(503).send('Service Temporary Ununavailable');
```suggestion
    res.status(503).send('Service Temporary Unavailable');
```

2023-07-31 08:26 UTC, rantan commented on backend/actions/transaction_detail.js
> +    res.status(503).send('Service Temporary Ununavailable');
```suggestion
    res.status(503).send('Service Temporary Unavailable');
```

2023-07-31 12:38 UTC, Yamaguchi commented on backend/actions/block_detail.js
> +    res.status(503).send('Service Temporary Ununavailable');
fix a0de50d8c92c84afb50780db8c2f157f3fd1115b

2023-07-31 12:38 UTC, Yamaguchi commented on backend/actions/transaction_detail.js
> +    res.status(503).send('Service Temporary Ununavailable');
fix a0de50d8c92c84afb50780db8c2f157f3fd1115b

2023-07-31 12:38 UTC, Yamaguchi commented on backend/actions/transaction_detail.js
> +    res.status(503).send('Service Temporary Ununavailable');
fix a0de50d8c92c84afb50780db8c2f157f3fd1115b

2023-07-31 12:38 UTC, Yamaguchi commented on backend/actions/transaction_detail.js
> +    res.status(503).send('Service Temporary Ununavailable');
fix a0de50d8c92c84afb50780db8c2f157f3fd1115b

2023-08-01 06:10 UTC, rantan approved these changes

2023-08-07 06:06 UTC, azuchi approved these changes

2023-08-07 06:06 UTC, merged