Feature/397 check balance of materials
chaintope/tapyrus-explorer pull request #144
Opened 2023-07-27 16:37 UTC by Yamaguchi

resolves #397

Show button to check balance of the tracking materials in transaction detail page.

2023-07-31 08:49 UTC, azuchi requested changes
追加した各actionについて、テストケースを追加してください。

2023-07-31 08:49 UTC, azuchi commented on backend/libs/util.js
> +  ) {
`validate.js`の`isValidFormat`関数にも同様の処理があるので、まとめた方がいいですね。

2023-08-01 01:37 UTC, rantan requested changes

2023-08-01 01:40 UTC, rantan commented on backend/actions/validate.js
> +app.get('/api/check_balance/:txid', async (req, res) => {
全体的にですが、`Tracking` という表現を使っている場所は `MaterialTracking` とした方が `Tracking v1` との混同がなくてよいと思います。

2023-08-01 14:45 UTC, Yamaguchi commented on backend/actions/validate.js
> +app.get('/api/check_balance/:txid', async (req, res) => {
9c6fd457a491723c83adc59a299be1641f5dec9d で修正してます。
ファイル名も `tracking_validation.module.ts` -> `material_tracking_validation.module.ts` のような変更を行っています。

2023-08-04 06:09 UTC, Yamaguchi commented
> 追加した各actionについて、テストケースを追加してください。

31785d0983230a22ce35a37e0c105c09b37f2cfe で対応してます

2023-08-04 06:09 UTC, Yamaguchi commented on backend/libs/util.js
> +  ) {
31785d0983230a22ce35a37e0c105c09b37f2cfe で対応してます

2023-08-04 06:40 UTC, azuchi approved these changes

2023-08-08 04:04 UTC, merged