Link to tx detail page from out point of inputs
chaintope/tapyrus-explorer pull request #157
Opened 2023-09-27 15:07 UTC by Yamaguchi

resolves #156 
Add links to the transaction input information so that the user can go to the detail page.

2023-09-29 04:32 UTC, rantan requested changes
アウトポイントを選択して遷移した後、選択されたアウトポイントまでスクロールする挙動は実装されていますが、ハイライトする挙動は実装されていないように見えます。

2023-09-29 12:21 UTC, Yamaguchi commented
> アウトポイントを選択して遷移した後、選択されたアウトポイントまでスクロールする挙動は実装されていますが、ハイライトする挙動は実装されていないように見えます。

背景色を変更しました。
65e16b4b8061f31f6d374ef1c2b88b9f55ea6676

2023-09-29 14:32 UTC, Yamaguchi commented
![Tapyrus-Explorer (2)](https://github.com/chaintope/tapyrus-explorer/assets/220267/ed36ee78-f0af-4ea1-87c2-075759a76e74)

2023-10-02 05:49 UTC, rantan approved these changes

2023-10-02 06:05 UTC, merged