Implement color list page
chaintope/tapyrus-explorer pull request #165
Opened 2024-03-17 18:56 UTC by Yamaguchi

resolve #55

2024-03-21 07:18 UTC, rantan commented
@Yamaguchi スクリーンショットを張ってもらえませんか？

2024-03-22 07:13 UTC, Yamaguchi commented
![Tapyrus-Explorer](https://github.com/chaintope/tapyrus-explorer/assets/220267/ea980def-1edd-4169-8c2c-a9af65910945)

2024-03-25 16:52 UTC, Yamaguchi commented
発行したコインの量を表示するようにしました。
![image](https://github.com/chaintope/tapyrus-explorer/assets/220267/bfc958ab-5bc7-4b22-8de1-73921aec5623)

2024-03-29 05:59 UTC, azuchi requested changes

2024-03-29 05:59 UTC, azuchi commented on frontend/src/app/colors/colors.page.html
> +        <ion-col size="3" class="pt-10">ISSUED</ion-col>
```suggestion
        <ion-col size="3" class="pt-10">TOTAL SUPPLY</ion-col>
```

2024-04-02 05:26 UTC, rantan approved these changes

2024-04-09 06:09 UTC, merged