Add '/backend' path all the apis in backend
chaintope/tapyrus-explorer pull request #84
Opened 2021-06-22 05:45 UTC by rantan

This is for deployment.

To recognize to be requests for backend in a load balancer. 
Some load balancers like ALB  are able to recoginize path to switch to forward the requests to targets.

2021-06-22 05:56 UTC, azuchi requested changes
I think `api` is better than `backend`, in fact it is api.

2021-06-22 08:26 UTC, rantan commented
Ok, I will change to 'api'

2021-06-23 01:55 UTC, azuchi commented on frontend/src/app/backend.service.ts
> +    return this.http.get(`${this.backendUrl}/backend/block/${blockHash}/raw`);
`backend` still remain.

2021-06-23 04:50 UTC, rantan commented on frontend/src/app/backend.service.ts
> +    return this.http.get(`${this.backendUrl}/backend/block/${blockHash}/raw`);
done

2021-06-23 05:07 UTC, azuchi approved these changes

2021-06-23 05:08 UTC, merged